package entities

import (
	"net/url"
	"strings"
)

type PermissionRequest struct {
	Header           map[string]string `json:"header" validate:"required"`
	Method           string            `json:"method" validate:"required"`
	RemoteAddr       string            `json:"remoteAddr" validate:"required"`
	URL              *url.URL          `json:"url" validate:"required"`
	RawBody          []byte            `json:"rawBody"`
	headerAttbsLower bool
}

func (c *PermissionRequest) GetHeader(name string) string {
	if !c.headerAttbsLower {
		for k, v := range c.Header {
			delete(c.Header, k)
			c.Header[strings.ToLower(k)] = v
		}
		c.headerAttbsLower = true
	}

	return c.Header[strings.ToLower(name)]
}

type TraceID struct {
	W3C string `json:"w3c"`
}

type AutoGenerated struct {
	WorkspaceName string  `json:"workspace_name"`
	TraceID       TraceID `json:"trace_id"`
}
